### ISSUE TITLE
What does "real-time simulation of a blockchain" mean?

### ISSUE THREAD

**Issue by nhooyr** [arunkirubarajan/not-so-lone-shark#1]
It'd be cool to have a more elaborate README.md for this project like your others, its not clear to me what it does or why it won the best security award.

There doesn't seem to be any implementation of a blockchain in the codebase.

**Comment by kirubarajan** [comment]
To be frank, I kinda forgot that this project existed and this may or may not be the codebase that we ended up being judged for.

If memory serves me right, we implemented a loaning system that used a public ledger. Proof-Of-Works weren't included in the original hackathon project but I think we had plans to implement something to make it more actually blockchain-y.

**Comment by nhooyr** [comment]
All good.
